### ISSUE TITLE
Warband Bank tab doesn't show  in the bottom tabs

### ISSUE THREAD

**Issue by tailcat** [Nevcairiel/Inventorian#35]
Even though its not ready yet when Inventorian is disabled it shows up in the bottom tabs next to Reagent Bank.

**Comment by Ramiru** [comment]
Warbank is fully available but Inventorian is not allowing any way to access it - hoping that the fix is in the works as it's blocking a full feature from TWW prepatch as it stands, @Nevcairiel any chance you can look into adding the warbank tab?

**Comment by nezorflame** [comment]
In the current (11.0.2.0) version Warband bank is working, but not fully implemented - for example, it doesn't show Warband gold storage and doesn't allow to deposit or withdraw money. Because of this, it's impossible to transfer gold using Inventorian.
Also, pressing right-click to deposit reagents from your bag to Warband bank tab doesn't work either - it shows error "Your reagent bank is full" (which it is not).

@Nevcairiel should we track this in the new issue or just continue this one?

**Comment by S1332** [comment]
> In the current (11.0.2.0) version Warband bank is working, but not fully implemented - for example, it doesn't show Warband gold storage and doesn't allow to deposit or withdraw money. Because of this, it's impossible to transfer gold using Inventorian. Also, pressing right-click to deposit reagents from your bag to Warband bank tab doesn't work either - it shows error "Your reagent bank is full" (which it is not).
> 
> @Nevcairiel should we track this in the new issue or just continue this one?

One week ago; any info if this is being worked on? kinda annoying issue

**Comment by Nevcairiel** [comment]
i've added support for the gold display and withdrawing/depositing, and tested right clicking items from my inventory, both reagents and otherwise, and they'll go into the warbank if thats the currently open tab for me.
