### ISSUE TITLE
About backpack item icon size

### ISSUE THREAD

**Issue by aixiu** [Nevcairiel/Inventorian#5]
It seems that the icon size of the backpack item is too big for the small screen. Is there a way to set it to the same icon size as the default backpack?

**Comment by Nevcairiel** [comment]
The icons automatically adjust their size to the size of the frame. If you make the frame larger, the icons will grow, and if you make it smaller, they'll shrink.

If you're creating a fresh character the items will also appear bigger because it doesn't want to present you with a load of empty space, they'll naturally shrink once you add more bags to your character.

I can possibly reduce the maximum size, so it doesn't appear quite as large.

**Comment by aixiu** [comment]
@Nevcairiel thx.Your answer makes me understand the principle.

**Comment by 0blu** [comment]
Just wanted to say that it took this issue to find out that the bag gui is resizable.
Maybe you could highlight this feature a litte better in the AddOn overview :)

I know that there is this already this text:
`You can resize the Inventorian frames by dragging the bottom right corner of any frame. The rows and columns of bag buttons will automatically adjust to fit the frame size you choose.`

**Comment by Nevcairiel** [comment]
How would you make it more obvious?
