### ISSUE TITLE
Classic Keyring

### ISSUE THREAD

**Issue by questionmarkquestionmark** [Nevcairiel/Inventorian#8]
Today wow classic updated to and added the keyring. Current version of classic inventorian doesn't support this, when you click the keyring it just opens the inventory and not a separate keyring window.

**Comment by kevbry** [comment]
For a quick fix, edit Inventorian.lua and change BAG_CONFIG:bags from:
{ BACKPACK_CONTAINER, 1, 2, 3, 4 }
to
{ KEYRING_CONTAINER, BACKPACK_CONTAINER, 1, 2, 3, 4 }

No idea if this is going to break something else, but I haven't had any issues so far.

**Comment by kevbry** [comment]
Pretty sure I have this working, is there anyone around to accept a PR?

**Comment by Nevcairiel** [comment]
Adding the keyring to the main bag window is not ideal, as it would be rather confusing to have an additional 16 slots there which you can't use for normal items.

I was planning to make a new window and add a key button to the bag frame, which I'll likely work on this weekend.

**Comment by Twizt3r** [comment]
Any news on this keyring update ?

**Comment by denisgenon** [comment]
No news ? :(

**Comment by sk42git** [comment]
Quick and very dirty temporary fix here. 
Keyring window shows some redundant information (currency and bag slot) but otherwise works. May have issues manually moving keys around, but right-clicking them should still work. 
Probably throws some new errors - you're on your own there. 
Can't test with a full keyring to make sure it resizes properly/etc, but I don't expect any problems with that. 
Added "/inventorian keys" command, just in case.

Links contain an updated Inventorian.lua (remove .txt. extension if you dl from git). Be sure to back up your original before replacing it.

[Inventorian.lua.txt](https://github.com/Nevcairiel/Inventorian/files/4555930/Inventorian.lua.txt)
https://pastebin.com/LRgNrL4F

**Comment by blastehh** [comment]
Check out my fork here, it's pretty much fully working https://github.com/blastehh/Inventorian

**Comment by Nevcairiel** [comment]
This is now available
